export function formatHelp({ defaultRuntimeHome } = {}) {
  return [
    'Crewline',
    '',
    'A gateway where humans and local AI agents collaborate.',
    '',
    'Usage:',
    '  crewline <command> [subcommand] [--force]',
    '',
    'Commands:',
    '  help                     Show this help',
    '  init [--force]           Create the default ~/.crewline initial config',
    '  start                    Start the gateway service',
    '  stop                     Stop the gateway service',
    '  restart                  Restart the gateway service',
    '  status                   Show service status',
    '  health                   Show health report',
    '  doctor                   Validate current config readiness',
    '  doctor telegram          Run Telegram-specific checks',
    '  doctor feishu           Run Feishu-specific checks',
    '  doctor wechat           Run WeChat-specific checks',
    '  install                  Install macOS launchd service',
    '  uninstall                Remove macOS launchd service',
    '  wechat login             Start first-time WeChat QR login',
    '  push <channel>           Send a proactive message to Telegram/Feishu/WeChat',
    '  trigger <channel>        Post a visible trigger message, then inject it into the bound Agent',
    '  session <list|reset>     List or reset stored Agent runtime sessions',
    '',
    'Config resolution:',
    `  1. CREWLINE_RUNTIME_HOME if set`,
    `  2. ${defaultRuntimeHome ?? '~/.crewline'}`,
    '',
    'Common flow:',
    '  crewline init',
    '  crewline help',
    '  crewline doctor',
    '  crewline start',
    '',
    'macOS service management:',
    '  `crewline start` uses launchd and installs the agent automatically when needed.',
    '  direct mode is reserved for local development entrypoints such as `npm run dev`.'
  ].join('\n');
}
