export function formatHelp({ defaultRuntimeHome } = {}) {
  return [
    'Crewline',
    '',
    'A gateway where humans and local AI agents collaborate.',
    '',
    'Usage:',
    '  crewline <command> [subcommand] [--force]',
    '',
    'Commands:',
    '  help                     Show this help',
    '  init [--force]           Create the default ~/.crewline initial config',
    '  start                    Start the gateway service',
    '  stop                     Stop the gateway service',
    '  restart                  Restart the gateway service',
    '  status                   Show service status',
    '  prod-start               Start the production launchd service',
    '  prod-stop                Stop the production launchd service',
    '  prod-restart             Restart the production launchd service',
    '  prod-status              Show production launchd service status',
    '  health                   Show health report',
    '  doctor                   Validate current config readiness',
    '  doctor telegram          Run Telegram-specific checks',
    '  doctor feishu           Run Feishu-specific checks',
    '  doctor wechat           Run WeChat-specific checks',
    '  install                  Install macOS launchd service for production use',
    '  uninstall                Remove macOS launchd service for production use',
    '  wechat login             Start first-time WeChat QR login',
    '',
    'Config resolution:',
    `  1. CREWLINE_RUNTIME_HOME if set`,
    `  2. ${defaultRuntimeHome ?? '~/.crewline'}`,
    '',
    'Common flow:',
    '  crewline init',
    '  crewline help',
    '  crewline doctor',
    '  crewline start'
  ].join('\n');
}
